- name: "{{ component }} | create config dir"
  ansible.builtin.file:
    path: ~/.config/git
    state: directory

- name: "{{ component }} | link config"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - src: "{{ playbook_dir }}/git/config"
      dest: ~/.config/git/config
    - src: "{{ lookup('env', 'HOMEBREW_PREFIX') }}/share/git-delta/themes.gitconfig"
      dest: ~/.config/git/config.themes
      enabled: "{{ lookup('env', 'HOMEBREW_PREFIX') | length > 0 }}"
  when: item.enabled | default(true)
