---
- hosts: localhost
  tasks:
    - name: Add Taps
      homebrew_tap: tap={{item}} state=present
      with_items:
        - homebrew/cask
    - name: Upgrade Homebrew packages
      homebrew: update_homebrew=yes upgrade_all=yes
    - name: Install Homebrew packages
      homebrew:
        name:
          - ack
          - gnu-sed
          - reattach-to-user-namespace
          - tmux
          - vimpager
          - zsh-completions
          - zsh-syntax-highlighting
        state: present
    - name: Install Homebrew Casks
      homebrew_cask: name={{item}} state=present
      with_items:
        - firefox
        - gimp
        - iina
        - sourcetree
    - name: Cleanup Homebrew
      shell: brew cleanup
