---
- hosts: localhost
  tasks:
    - name: Check if Homebrew is installed
      stat: path=/usr/local/bin/brew
      register: brew_installed
    - name: Install Homebrew
      shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
      when: brew_installed.stat.exists == false
    - name: Add Taps
      homebrew_tap: tap={{item}} state=present
      with_items:
        - caskroom/cask
    - name: Upgrade Homebrew packages
      homebrew: update_homebrew=yes upgrade_all=yes
    - name: Install Homebrew packages
      homebrew: name={{item}} state=present
      with_items:
        - ack
        - gnu-sed
        - reattach-to-user-namespace
        - ssh-copy-id
        - tmux
        - vimpager
        - zsh-completions
        - zsh-syntax-highlighting
    - name: Install Homebrew Casks
      homebrew_cask: name={{item}} state=present
      with_items:
        - atom
        - dropbox
        - firefox
        - gimp
        - google-chrome
        - macvim
        - sourcetree
        - vlc
    - name: Cleanup Homebrew
      shell: brew cask cleanup && brew cleanup
