---
- hosts: localhost
  tasks:
    - name: Add Taps
      homebrew_tap: tap={{item}} state=present
      with_items:
        - caskroom/cask
    - name: Upgrade Homebrew packages
      homebrew: update_homebrew=yes upgrade_all=yes
    - name: Install Homebrew packages
      homebrew: name={{item}} state=present
      with_items:
        - ack
        - gnu-sed
        - reattach-to-user-namespace
        - tmux
        - vimpager
        - zsh-completions
        - zsh-syntax-highlighting
    - name: Install Homebrew Casks
      homebrew_cask: name={{item}} state=present
      with_items:
        - dropbox
        - gimp
        - google-chrome
        - sourcetree
        - vlc
    - name: Cleanup Homebrew
      shell: brew cask cleanup && brew cleanup
