---
- hosts: localhost
  tasks:
    - name: Check if Homebrew is installed
      stat: path=/usr/local/bin/brew
      register: brew_installed
    - name: Install Homebrew
      shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
      when: brew_installed.stat.exists == false
    - name: Tap Homebrew Cask
      homebrew_tap: tap=caskroom/cask state=present
    - name: Upgrade Homebrew packages
      homebrew: update_homebrew=yes upgrade_all=yes
    - name: Install Homebrew packages
      homebrew: name={{item}} state=present
      with_items:
        - ack
        - brew-cask
        - httpie
        - reattach-to-user-namespace
        - ssh-copy-id
        - tmux
        - vimpager
        - zsh-completions
    - name: Install Homebrew Casks
      homebrew_cask: name={{item}} state=present
      with_items:
        - dropbox
        - firefox
        - gimp
        - github-desktop
        - libreoffice
        - macvim
        - sourcetree
        - vlc
