" Vim configuration file.
"
" Location: ~/.vimrc
"
" Simon Olofsson <simon@olofsson.de>
"

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Show the line numer relative to the current line
set relativenumber

" Use two spaces for a tab
set tabstop=2 shiftwidth=2

" Don't insert two spaces when joining lines
set nojoinspaces

" Completion mode that is used in insert mode
set completeopt=longest,menu
" Completion mode that is used on the command line
set wildmode=longest,list

" Highlight the previous search pattern
set hlsearch
" Ignore case in search patterns
set ignorecase
" Override 'ignorecase' if the search pattern contains upper case characters
set smartcase

" Keep backup files
set backup
" Enable undo persistence
set undofile
" Store everything under ~/.vim
set backupdir^=~/.vim/backup/
set directory^=~/.vim/swap/
set viminfo+=n~/.vim/viminfo
set undodir^=~/.vim/undo/

" Appearance
if system("defaults read -g AppleInterfaceStyle") =~ "^Dark"
	set background=dark
else
	set background=light
endif
let g:solarized_termtrans = 1
colorscheme solarized8
let g:lightline = {
			\ 'colorscheme': 'solarized',
			\ }
" Lightline shows the mode already
set noshowmode
