" Vim configuration file.
"
" Location: ~/.vimrc
"
" Simon Olofsson <simon@olofsson.de>
"

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Optional packages shipped with Vim
" comment:      gc/gcc/gC comment toggling and the ic/ac text objects
" editorconfig: apply settings from .editorconfig files
" hlyank:       briefly highlight the yanked text
packadd! comment
packadd! editorconfig
packadd! hlyank

" Use the system clipboard
set clipboard^=unnamed

" Show the absolute line number for the current line
" and the relative line number for the other lines
set number
set relativenumber

" Use two spaces for a tab
set tabstop=2 shiftwidth=2

" Don't insert two spaces when joining lines
set nojoinspaces

" Completion mode that is used in insert mode
set completeopt=longest,menu
" Completion mode that is used on the command line
set wildmode=longest,list

" Highlight the previous search pattern
set hlsearch
" Ignore case in search patterns
set ignorecase
" Override 'ignorecase' if the search pattern contains upper case characters
set smartcase

" Clear the highlighting when entering insert mode. Going through feedkeys() is
" necessary because :nohlsearch has no effect when run from an autocmd.
augroup so_nohlsearch
  autocmd!
  autocmd InsertEnter * if v:hlsearch | call feedkeys("\<Cmd>nohlsearch\<CR>", 'm') | endif
augroup END

" Keep backup files
set backup
" Enable undo persistence
set undofile
" Store everything under ~/.vim
set backupdir^=~/.vim/backup/
set directory^=~/.vim/swap/
set undodir^=~/.vim/undo/
set viminfofile=~/.vim/viminfo

" Don't blink in normal mode
let g:togglecursor_default = 'block'

" Sneak: show labels and replace the default f/F/t/T mappings
let g:sneak#label = 1
map f <Plug>Sneak_f
map F <Plug>Sneak_F
map t <Plug>Sneak_t
map T <Plug>Sneak_T

" Signify: always show the sign column, so the text never shifts
set signcolumn=yes

" Signify updates the signs on CursorHold, so keep 'updatetime' short
set updatetime=100

" Appearance

" Enable 24-bit colors
set termguicolors

" Get the theme from the environment
const [s:appearance, s:colorscheme] = $SO_VIM_THEME->split()
execute "set background=" . s:appearance
execute "colorscheme " . s:colorscheme
let g:lightline = { 'colorscheme': s:colorscheme }

" Lightline shows the mode already
set noshowmode
