# Zsh config for login shells.
#
# Location: ~/.zprofile
#
# Simon Olofsson <simon@olofsson.de>
#

test -x /opt/homebrew/bin/brew && eval "$(/opt/homebrew/bin/brew shellenv)"

if type brew &>/dev/null; then
  fpath+="$(brew --prefix)/share/zsh/site-functions"
  fpath+="$(brew --prefix)/share/zsh-completions"
fi

test -d "$HOME/.zfunc" && fpath+="$HOME/.zfunc"

export EDITOR='vim'

# Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
export KEYTIMEOUT=1

# Make less more usable
export LESS="--ignore-case --no-histdups --color=s+y"

# Use bat as manpager
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Config file for ripgrep
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

# Additional args for compinit, can be overriden in .zprofile.local
export SO_COMPINIT_ARGS=''

test -f "$HOME/.zprofile.local" && source "$HOME/.zprofile.local"
