# Zsh config for interactive shells.
#
# Location: ~/.zshrc
#
# Simon Olofsson <simon@olofsson.de>
#

for f in $HOME/.zsh/[[:digit:]]*_*.zsh; do
	source $f;
done

# Only available on Ubuntu
[[ -f /etc/zsh_command_not_found ]] && source /etc/zsh_command_not_found
