# Zsh config for interactive shells.
#
# Location: ~/.zshrc
#
# Simon Olofsson <simon@olofsson.de>
#

for f in $HOME/.zsh/[[:digit:]]*_*.zsh; do
	source $f;
done

source $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/.zsh/syntax-highlighting.zsh

# Only available on Ubuntu
if [[ -f /etc/zsh_command_not_found ]]; then
	source /etc/zsh_command_not_found
fi
